adminLogin = admin
AdminPass = admin123
baseUrl = https://opensource-demo.orangehrmlive.com/web/index.php/auth/login
DBurl = jdbc:postgresql://86.57.161.116:50432/register_office
user = user
password = user-senla